name: Mocha API Test

on:
  push:
    branches:
      - main
      - issue-*
  pull_request:
    branches:
      - main
      - issue-*
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 20.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: Set up environment variables
      run: |
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
        echo "PARAM_URL=${{ secrets.PARAM_URL }}" >> $GITHUB_ENV
        echo "BOOKING_URL=${{ secrets.BOOKING_URL }}" >> $GITHUB_ENV
        echo "USER_NAME=${{ secrets.USER_NAME }}" >> $GITHUB_ENV
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
    
    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

    - name: Debug Test Report
      run: cat reports/test-results.json
